#!/bin/bash
export DJANGO_LOGLEVEL=DEBUG \
DJANGO_DEBUG=True \
ALLOWED_HOSTS=* \
HASH_LENGTH=256 \
SALT=abc123!? \
IV=abcdefg \
DB_NAME=tadb \
DB_USER=taadmin \
DB_PASSWORD=taadmin \
DB_HOST=127.0.0.1 \
DB_PORT=5432