# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-15 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='w',
        ),
    ]
