# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-15 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191015_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='body',
            new_name='fileno',
        ),
    ]
