# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-15 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191015_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
    ]
