# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-15 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_note_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='FileNo',
        ),
    ]
