# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-15 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191015_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileno',
            name='fileno',
            field=models.IntegerField(),
        ),
    ]
