# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-23 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191015_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.CharField(max_length=200)),
                ('searchno', models.IntegerField()),
            ],
        ),
    ]
