# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-24 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_searchno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileno',
            name='w',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='searchno',
            name='w',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
