# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-27 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191024_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileno',
            name='w',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='searchno',
            name='w',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
