// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#ifndef SAMPLES_REMOTE_ATTESTATION_PUBKEY_H
#define SAMPLES_REMOTE_ATTESTATION_PUBKEY_H

static const char OTHER_ENCLAVE_PUBLIC_KEY[] =
    "-----BEGIN PUBLIC KEY-----\n"
    "MIIBoDANBgkqhkiG9w0BAQEFAAOCAY0AMIIBiAKCAYEAq4lib5qQJLKKsBG1usMK\n"
    "9THUUcKD/cDPvAockdNI3WegzIgmvfCaN+LPT9rN0/qhlLShtnbY83vFwcNl8V9w\n"
    "evIuEezIB/VuA66N5YG+GD/cBG0TOHymiAM3gn8sbKdQbDdO6DAn5Z1XgbP7l9Y7\n"
    "5oTCER32SMnrQWsgcrAXh3G8k7Re4NAG0hNipZ4444KamLGMqjjnYYxHUosD3UE1\n"
    "aZm6HMlTiL17Gc/9rl3hBSBgsfFJbnglpbw+KxQ6zUBmVRxp8paTFM8LR50cuOzH\n"
    "YRXjxpWJAMzRlXpjPZwEEhQU5qyX4wL2juAYsPjeChv1ZCO6rTSU3ItPIy0056+4\n"
    "HnzzZT1Dq/RwXUOSSiRDzK6dB8pA3+JWavPJWDNSVv0On/lO7W+JHQsqNXsV95R4\n"
    "xwYtgbffsWykI0of5395OvAAvX6xWjUnlpjRhYZXjZh109MSWqUKFuyigRxu+oAb\n"
    "cEsF9Wr5FyZSZ3qbV6sEPhtL36RrBS4e1ubiVrxbNqJBAgED\n"
    "-----END PUBLIC KEY-----\n";

#endif /* SAMPLES_REMOTE_ATTESTATION_PUBKEY_H */
